

# Specify the compiler options or flags, linking libraries
# and any debugging information flags as a variables
CC = gcc

#
# Specify the target
all: mdeshpa1_phone_directory


# Specify how the executables should be created from source files
mdeshpa1_phone_directory: mdeshpa1_phone_directory.c
			  $(CC) mdeshpa1_phone_directory.c -o mdeshpa1_phone_directory.out 

# Specify the object files and executables that are generated
# and need to be removed to re-compile the whole thing
clean:
	rm -f mdeshpa1_phone_directory.out




